### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot set a request body for a PUT method

### ISSUE THREAD

**Issue by buep** [Praqma/quticon_visualization#16] opened 2017-02-06 13:12 UTC
```
New entry: name randomfailingjob, result SUCCESS, number 3, duration 12, timestamp 1486383540282, time in queue 1
[Pipeline] echo
New entry: name randomfailingjob, result SUCCESS, number 2, duration 15, timestamp 1486383480286, time in queue 1
[Pipeline] echo
New entry: name randomfailingjob, result SUCCESS, number 1, duration 1192, timestamp 1486383403100, time in queue 6
[Pipeline] echo
Posting mappings to http://10.20.8.23:9200/jenkins: { "mappings" : { "_default_" : { "properties" : { 
                                                                  "verdict" : {"type": "string"},
                                                                  "job_name" : {"type": "string"},
                                                                  "build_number" : {"type": "integer"},
                                                                  "duration" : {"type": "integer"},
                                                                  "timestamp" : {"type": "date"},
                                                                  "time_in_queue" : {"type": "integer"}
  }}}}
[Pipeline] End of Pipeline
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
java.lang.IllegalArgumentException: Cannot set a request body for a PUT method
	at groovyx.net.http.HTTPBuilder$RequestConfigDelegate.encodeBody(HTTPBuilder.java:1258)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:442)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:434)
	at groovyx.net.http.HTTPBuilder.request(HTTPBuilder.java:383)
```

Using Jenkins 2.7.4, running in a container on Ubuntu.

Defined global shared groovy lib, so the pipeline job seems to work.

**Comment by buep** [comment] 2017-02-06 14:50
@Library('quticon_visualization')
import net.praqma.quticon.BuildDataEntry
def data = jenkinsExtractor(["randomfailingjob"], 5)
pushToELK("http://10.20.8.23:9200", "jenkins", data)

**Comment by buep** [comment] 2017-02-06 14:54
```
Started by user admin
Loading library quticon_visualization@0.2
 > git rev-parse --is-inside-work-tree # timeout=10
Setting origin to https://github.com/praqma/quticon_visualization.git
 > git config remote.origin.url https://github.com/praqma/quticon_visualization.git # timeout=10
Fetching origin...
Fetching upstream changes from origin
 > git --version # timeout=10
 > git fetch --tags --progress origin +refs/heads/*:refs/remotes/origin/* +refs/pull/*/head:refs/remotes/origin/pr/*
 > git rev-parse 0.2^{commit} # timeout=10
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from 2 remote Git repositories
 > git config remote.origin.url https://github.com/praqma/quticon_visualization.git # timeout=10
Fetching upstream changes from https://github.com/praqma/quticon_visualization.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/praqma/quticon_visualization.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin1.url https://github.com/praqma/quticon_visualization.git # timeout=10
Fetching upstream changes from https://github.com/praqma/quticon_visualization.git
 > git fetch --tags --progress https://github.com/praqma/quticon_visualization.git +refs/pull/*/head:refs/remotes/origin/pr/*
Checking out Revision 2b73caafe38fbbd2fd6f9c071785e9b18e547f32 (0.2)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 2b73caafe38fbbd2fd6f9c071785e9b18e547f32
 > git rev-list a949fcfb3ee9a511e3bc21ee52324182d511f29a # timeout=10
```

**Comment by buep** [comment] 2017-02-06 15:08
ES tells jenkins index doesn't exists, but that shouldn't matter.

If I create it... e.g. like this, the error is still the same.

```
$ curl -XPUT 'http://10.20.8.23:9200/jenkins/'
{"acknowledged":true,"shards_acknowledged":true}
```


```
New entry: name randomfailingjob, result SUCCESS, number 1, duration 1192, timestamp 1486383403100, time in queue 6
[Pipeline] echo
Posting mappings to http://10.20.8.23:9200/jenkins: { "mappings" : { "_default_" : { "properties" : { 
                                                                  "verdict" : {"type": "string"},
                                                                  "job_name" : {"type": "string"},
                                                                  "build_number" : {"type": "integer"},
                                                                  "duration" : {"type": "integer"},
                                                                  "timestamp" : {"type": "date"},
                                                                  "time_in_queue" : {"type": "integer"}
  }}}}
[Pipeline] End of Pipeline
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
java.lang.IllegalArgumentException: Cannot set a request body for a PUT method
	at groovyx.net.http.HTTPBuilder$RequestConfigDelegate.encodeBody(HTTPBuilder.java:1258)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:442)
```

**Comment by buep** [comment] 2017-02-06 15:22
From another Jenkins job, this works:

```
Started by user admin
Building in workspace /var/jenkins_home/workspace/curl-check
[curl-check] $ /bin/sh -xe /tmp/hudson9095119728234372773.sh
+ curl http://10.20.8.23:9200
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   327  100   327    0     0   243k      0 --:--:-- --:--:-- --:--:--  319k
{
  "name" : "YDRA5om",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "aNmdnPRlQDmlzlqsojzY6g",
  "version" : {
    "number" : "5.2.0",
    "build_hash" : "24e05b9",
    "build_date" : "2017-01-24T19:52:35.800Z",
    "build_snapshot" : false,
    "lucene_version" : "6.4.0"
  },
  "tagline" : "You Know, for Search"
}
Finished: SUCCESS
```

So connectivity should be okay.

**Comment by Andrey9kin** [comment] 2017-02-06 17:05
@buep there seems to be something with the Groovy method call - pipeline simply fails when trying to create mappings and no data being loaded. Do you have a possibility to try latest LTS Jenkins? Just to make sure that we have the same env/plugins. Also, please share your plugins.txt

**Comment by buep** [comment] 2017-02-06 23:02
Same problem with jenkins 2.32.2 version, and latest of all relevant plugins. I don't have a plugin.txt.

Do you have any bindings or dependencies not mentioned in the README?

**Comment by buep** [comment] 2017-02-06 23:03
It seems like I have data by the way... can I check that somehow? My debug prints shows I have something.

**Comment by Andrey9kin** [comment] 2017-02-07 10:02
@buep that is weird - works just fine for the customer and I did a demo with the Jenkins as code last Friday. So I'm not even sure how to reproduce it so we can fix it.

Could you please check system log if there are more info there? Usually, pipelines are very quiet in UI but drop a lot of stack traces to the system log. docker logs should do it

**Comment by buep** [comment] 2017-02-07 10:18
What version did you use of the quticon project?
What version of JEnkins, and plugins?

**Comment by Andrey9kin** [comment] 2017-02-07 10:19
quticon is the same as you - 0.2
we are using what is in Jenkins as Code repo on the master branch

**Comment by buep** [comment] 2017-02-07 10:21
the praqma jenkins as code repo?

The log shows nothing from the container:

```
Feb 07, 2017 10:20:14 AM org.jenkinsci.plugins.workflow.job.WorkflowRun finish
INFO: elk-collector #66 completed: FAILURE
Feb 07, 2017 10:20:14 AM jenkins.plugins.model.JobFailedTimeInfo recordFailedTimeInfo
INFO: last7days buildCount : 0

Feb 07, 2017 10:20:14 AM jenkins.plugins.model.JobFailedTimeInfo recordFailedTimeInfo
INFO: last7days totalFailedTime : 0 ms

Feb 07, 2017 10:20:14 AM jenkins.plugins.model.JobFailedTimeInfo recordFailedTimeInfo
INFO: last7days average failed  time : 0 ms

Feb 07, 2017 10:20:14 AM jenkins.plugins.model.JobFailedTimeInfo recordFailedTimeInfo
INFO: last30days buildCount : 0

Feb 07, 2017 10:20:14 AM jenkins.plugins.model.JobFailedTimeInfo recordFailedTimeInfo
INFO: last30days totalFailedTime : 0 ms

Feb 07, 2017 10:20:14 AM jenkins.plugins.model.JobFailedTimeInfo recordFailedTimeInfo
INFO: last30days average failed  time : 0 ms

Feb 07, 2017 10:20:14 AM jenkins.plugins.model.JobFailedTimeInfo recordFailedTimeInfo
INFO: allBuilds buildCount : 0

Feb 07, 2017 10:20:14 AM jenkins.plugins.model.JobFailedTimeInfo recordFailedTimeInfo
INFO: allBuilds totalFailedTime : 0 ms

Feb 07, 2017 10:20:14 AM jenkins.plugins.model.JobFailedTimeInfo recordFailedTimeInfo
INFO: allBuilds average failed  time : 0 ms
```

**Comment by Andrey9kin** [comment] 2017-02-07 10:25
this one https://github.com/Praqma/JenkinsAsCodeReference

**Comment by buep** [comment] 2017-02-07 10:27
So what to do from here if I don't want to run jenkinsAsCode right now?

**Comment by buep** [comment] 2017-02-07 10:28
Your scripts will run as plain groovy code - right? So I could just mix up my own groovy script instead I guess?

**Comment by Andrey9kin** [comment] 2017-02-07 10:44
if you remove echo then yes. echo is pipeline specific

**Comment by buep** [comment] 2017-02-07 10:45
okay - I will consider my next steps.

**Comment by carmosin** [comment] 2017-02-07 12:14
Seems this is the piece of code that throws:

https://searchcode.com/codesearch/view/15771970/

` /**
         * Set the request body.  This value may be of any type supported by
         * the associated {@link EncoderRegistry request encoder}.  That is,
         * the value of <code>body</code> will be interpreted by the encoder
         * associated with the current {@link #getRequestContentType() request
         * content-type}.
         * @see #send(Object, Object)
         * @param body data or closure interpreted as the request body
         */
        public void setBody( Object requestContentType, Object body ) {
            if ( ! (request instanceof HttpEntityEnclosingRequest ) )
                throw new IllegalArgumentException(
                        "Cannot set a request body for a " + request.getMethod() + " method" );
            Closure encoder = encoders.getAt( requestContentType );
            HttpEntity entity = (HttpEntity)encoder.call( requestContentType, body );

            ((HttpEntityEnclosingRequest)this.request).setEntity( entity );
        }   `

This is what's happening in the pushtoelk.groovy

` http.request( PUT, JSON ) { req ->
    body = mappings
    uri.path = "/${index}"
     
    response.success = { resp, json ->
        println "Success! ${resp.status}"
    }

    response.failure = { resp ->
        println "Request failed with status ${resp.status}"
    } `

I've googled some to find if anyone else has seen a similar problem.  I found this:

http://stackoverflow.com/questions/2823590/post-with-httpbuilder-nullpointerexception

**Comment by buep** [comment] 2017-02-07 12:44
Thanks, but I did try the 1.7.2 version also... but what still is interesting is why it works for you.

Anyway, maybe I will work on this during the code café tonight.

**Comment by carmosin** [comment] 2017-02-07 12:53
Did you try specifically setting the content type?

Is there anyway I can have your environment?

**Comment by buep** [comment] 2017-02-07 13:07
If it doesnt' work tonight, where I will be using Jenkins as code you can have the environment.
I'm not using jenkinsascode at my customer (yet), so environment is not reproducible complete except from the plugins versions mentioned and jenkins version and using docker container.

**Comment by carmosin** [comment] 2017-02-07 14:14
> reproducible complete except from the plugins versions mentioned and jenkins version and using docker container

I guess this might be enough to reproduce the problem.  Would you like me to proceed with trying to reproduce the fault, or should I wait until you've tried jenkinsascode?

**Comment by buep** [comment] 2017-02-10 08:05
Problem still there, tried many of the suggestions on the SO answers, can get it to work.
My environment is the same though.

Made a fork to experiment, here are the experiments in commits: https://github.com/buep/quticon_visualization/commits/master

Most of them, except from few groovy issues, still get the same error ... cannet set request body for a post method.

**Comment by buep** [comment] 2017-02-10 08:08
At the moment I don't like to try JenkinsAsCode, as I need this to run in the customer environment.

**Comment by carmosin** [comment] 2017-02-13 12:11
@buep Did you have any progress?

**Comment by buep** [comment] 2017-03-06 15:09
It works using latest JenkinsAsCode, so my questions is what you depend on that you include with JenkinsAsCode ?
Do you install any customer groovy or java stuff?

**Comment by buep** [comment] 2017-03-28 08:25
@Andrey9kin @carmosin - you're the maintainers... any inputs to the above?

**Comment by buep** [comment] 2017-04-05 21:16
ping ?

**Comment by buep** [comment] 2017-04-28 14:52
Seems to work in latest version, and some random 2.0 jenkins...

**Closed** 2017-06-28 07:37 UTC
Labels: Action - awaiting feed-back
